version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "tailor-inc/developer"
    assignees:
      - "tailor-inc/developer"
  - package-ecosystem: "pip"
    directory: "get-ghe-access-token"
    schedule:
      interval: "daily"
    reviewers:
      - "tailor-inc/developer"
    assignees:
      - "tailor-inc/developer"
