name: 'notify-to-slack'
description: 'Notify job result to slack'

inputs:
  title:
    description: 'Title of the message'
    required: false
    default: 'Build'
  webhook_url:
    description: 'Slack webhook url'
    required: true

runs:
  using: composite
  steps:
    - name: Slack Notification on Failure
      # Composite actions cannot obtain job results from custom functions such as success() and failure(), so the job.status string is used as the judgment condition.
      if: job.status == 'failure'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: ${{ github.repository }} ${{ inputs.title }} Failed
        SLACK_COLOR: danger
        SLACK_WEBHOOK: ${{ inputs.webhook_url }}
