name: 'notify-to-slack'
description: 'Notify job result to slack'

inputs:
  title:
    description: 'Title of the message'
    required: false
    default: 'Build'
  webhook_url:
    description: 'Slack webhook url'
    required: true

runs:
  using: composite
  steps:
    - name: Slack Notification on Success
      # if: ${{ success() }}
      if: job.status == 'success'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: ${{ github.repository }} ${{ inputs.title }} Succeeded
        SLACK_COLOR: good
        SLACK_WEBHOOK: ${{ inputs.webhook_url }}

    - name: Slack Notification on Failure
      # if: ${{ failure() }}
      if: job.status == 'failure'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: ${{ github.repository }} ${{ inputs.title }} Failed
        SLACK_COLOR: danger
        SLACK_WEBHOOK: ${{ inputs.webhook_url }}

    - name: Dump GitHub context
      id: github_context_step
      shell: bash
      run: echo "github context" && echo '${{ toJSON(github) }}'
    - name: Dump job context
      shell: bash
      run: echo "job context" && echo '${{ toJSON(job) }}'
    - name: Dump steps context
      shell: bash
      run: echo "steps context" && echo '${{ toJSON(steps) }}'
    - name: Dump runner context
      shell: bash
      run: echo "runner context" && echo '${{ toJSON(runner) }}'
    - name: Dump strategy context
      shell: bash
      run: echo "strategy context" && echo '${{ toJSON(strategy) }}'
    - name: Dump matrix context
      shell: bash
      run: echo "matrix context" && echo '${{ toJSON(matrix) }}'
