name: get access token
description: 'Get access token via GitHub App'

inputs:
  app-id:
    required: true
    description: 'github app id'
  app-installation-id:
    required: true
    description: 'github app installation id'
  app-private-key:
    required: true
    description: 'github app private key'

outputs:
  access_token:
    description: 'access token'

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_APP_ID: ${{ inputs.app-id }}
    GITHUB_APP_INSTALLATION_ID: ${{ inputs.app-installation-id }}
    GITHUB_APP_PRIVATE_KEY: ${{ inputs.app-private-key }}

