name: get access token
description: 'Get access token via GitHub App'

inputs:
  setup-python:
    required: false
    default: 'true'
    description: 'Setup python'
  github-app-id:
    required: true
    description: 'github app id'
  github-app-installation-id:
    required: true
    description: 'github app installation id'
  github-app-private-key:
    required: true
    description: 'github app private key'

outputs:
  access_token:
    value: ${{ steps.get_access_token.outputs.access_token }}
    description: 'access token'

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_APP_ID: ${{ inputs.github-app-id }}
    GITHUB_APP_INSTALLATION_ID: ${{ inputs.github-app-installation-id }}
    GITHUB_APP_PRIVATE_KEY: ${{ inputs.github-app-private-key }}

