name: 'setup-go-with-docker'
description: 'Install go and docker build essential'
inputs:
  go-version:
    description: 'Version of go to install'
    required: true
    default: '^1.17'
runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash
      run: |
        apt update && apt install -y make build-essential ca-certificates curl gnupg lsb-release git
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt update
        apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-latest
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: set up go
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
