name: get release tag
description: 'Get latest release tag'

inputs:
  github_token:
    required: true
    description: 'github token'
  github_repo_owner:
    required: true
    description: 'github repo owner'
  github_repo_name:
    required: true
    description: 'github repo name'
  prerelease:
    required: false
    description: 'if set this value to true, the action will get the latest prerelease tag. Otherwise, it will get the latest release tag'
    default: 'false'

outputs:
  release_tag:
    value: ${{ steps.get-tag.outputs.release_tag }}
    description: 'release tag'

runs:
  using: "composite"
  steps:
    - name: get release with tag
      id: get-tag
      shell: bash
      run: |
        echo "release_tag=$(curl -s --header 'Authorization: Bearer ${{ inputs.github_token }}' https://api.github.com/repos/${{ inputs.github_repo_owner }}/${{ inputs.github_repo_name }}/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT
    - name: confirm release tag
      shell: bash
      run: |
        echo ${{ steps.get-tag.outputs.release_tag }}
