name: "Only build"
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    types: [reopened, closed]

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - name: Install go build-essential
        uses: tailor-inc/github-actions/setup-go-build-essential@22.08q

      - name: Notify to slack build result
        uses: tailor-inc/github-actions/slack-notification@22.08
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
